---

- name: Launch a compute instance and connect to it using SSH
  hosts: localhost
  gather_facts: true
  collections:
    - oracle.oci
    - community.general

  tasks:

    - name: Launch an instance
      oci_compute_instance:
        availability_domain: "{{ instance_ad }}"
        compartment_id: "{{ instance_compartment }}"
        name: "{{ instance_name }}"
        image_id: "{{ instance_image }}"
        shape: "{{ instance_shape }}"
        create_vnic_details:
            assign_public_ip: "{{ public_ip }}"
            hostname_label: "{{ instance_name }}"
            subnet_id: "{{ instance_subnet_id }}"
            private_ip: "{{ instance_ip }}"
        metadata:
            ssh_authorized_keys: "{{ ssh_public_key }}"
        freeform_tags: "{{ my_tags }}"
      register: result

    - name: print result to console
      debug:
        msg: "{{result}}"
