---

- name: Launch a compute instance and connect to it using SSH
  hosts: localhost
  gather_facts: true
  collections:
    - oracle.oci
    - community.general
  vars_files:
    - default_vars.yml

  tasks:
    - block:
      - set_fact:
          SSH_AUTHORIZED_KEYS: "{{ lookup('env', 'SAMPLE_PUBLIC_SSH_KEY') if 'SAMPLE_PUBLIC_SSH_KEY' in ansible_env else lookup('file',  my_test_public_key ) }}"

      - name: Launch an instance
        oci_compute_instance:
          availability_domain: "{{ instance_ad }}"
          compartment_id: "{{ instance_compartment }}"
          name: "{{ item.value.instance_name }}"
          image_id: "{{ instance_image }}"
          shape: "{{ instance_shape }}"
          create_vnic_details:
              assign_public_ip: "{{ item.value.public_ip }}"
              hostname_label: "{{ item.value.instance_name }}"
              subnet_id: "{{ instance_subnet_id }}"
              private_ip: "{{ item.value.instance_ip }}"
          metadata:
              ssh_authorized_keys: "{{ SSH_AUTHORIZED_KEYS }}"
        register: result
        loop: "{{ lookup('dict', compute_instances, wantlist=True) }}"

