---
- hosts: olvm
  become: yes
  become_method: sudo
  gather_facts: yes

  vars_files:
    - default_vars.yml

  tasks:

    - name: Login to OLVM manager
      ovirt_auth:
        url: "{{ lookup('env', 'OVIRT_URL') }}"
        username: "{{ lookup('env', 'OVIRT_USERNAME') }}"
        password: "{{ lookup('env', 'OVIRT_PASSWORD') }}"
        ca_file: "{{ olvm_cafile | default('/etc/pki/ovirt-engine/ca.pem') }}"
        insecure: "{{ olvm_insecure | default(true) }}"
      tags:
        - always

    - name: Tag Virtual Machine
      ansible.builtin.include_tasks: "task_tag_vm.yml"
      loop: "{{ groups['instances'] }}"
      loop_control:
        loop_var: vm_node

    - name: Cleanup OLVM auth token
      ovirt.ovirt.ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
