---

# Configure default_vars.yml to setup default infrastrcuture variables
#
# Define following variables as extra-vars:
#   --extra-vars "kvm_host_name=KVM1"
#   --extra-vars "kvm_host_fqdn=kvm1.demo.local"
#   --extra-vars "kvm_host_pwd=CHANGE_ME"

- hosts: olvm
  become: yes
  
  vars_files:
    - default_vars.yml

  tasks:

    - name: Login to OLVM manager
      ovirt_auth:
        url: "{{ lookup('env', 'OVIRT_URL') }}"
        username: "{{ lookup('env', 'OVIRT_USERNAME') }}"
        password: "{{ lookup('env', 'OVIRT_PASSWORD') }}"
        ca_file: "{{ olvm_cafile | default('/etc/pki/ovirt-engine/ca.pem') }}"
        insecure: "{{ olvm_insecure | default(true) }}"
      tags:
        - always

    - name: Add KVM host to the cluster
      ovirt.ovirt.ovirt_host:
        auth: "{{ ovirt_auth }}"
        cluster: Homelab
        name: "{{ kvm_host_name }}"
        address: "{{ kvm_host_fqdn }}"
        password: "{{ kvm_host_pwd }}"
        timeout: 1200

    - name: Cleanup OLVM auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
