---

- name: Remove the ASM disks and VM nodes on the OLVM cluster
  hosts: olvm
  become: yes
  become_method: sudo
  vars_files:
    - default_vars.yml

  tasks:
    - name: Verify if it is OK to destroy the Oracle DB VM
      ansible.builtin.pause:
        prompt: |
          WARNING!!!....Playbook paused...are you sure you want to destroy the Oracle DB VM?
          Hit <ctrl-c> then <a> to abort the playbook (and keep your Oracle DB VM safe)..
          Hit <enter> to continue and your Oracle DB VM (including ASM disks) will be destroyed.

    - name: Login to OLVM manager
      ovirt_auth:
        url: "{{ lookup('env', 'OVIRT_URL') }}"
        username: "{{ lookup('env', 'OVIRT_USERNAME') }}"
        password: "{{ lookup('env', 'OVIRT_PASSWORD') }}"
        ca_file: "{{ olvm_cafile | default('/etc/pki/ovirt-engine/ca.pem') }}"
        insecure: "{{ olvm_insecure | default(true) }}"
      tags:
        - always

    - name: Delete the single instance VM
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        state: absent
        name: "{{ vm_name }}"

    - name: "Delete the shareable disk {{ item }}"
      ovirt.ovirt.ovirt_disk:
        auth: "{{ ovirt_auth }}"
        name: "{{ item }}"
        state: absent
      with_items:
        - "{{ asm_disks }}"
      when:
        - vm_ha == true

    - name: Cleanup OLVM auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
