---

# Before running the playbook, configure default_vars.yml first to setup
# default infrastrcuture variables
#

- name: Generate SSH keys and configuration files before building VMs
  hosts: olvm
  gather_facts: no
  vars:
    nodes: ""
    nodeips: ""
    nodeprivs: ""
    nodeprivips: ""
    nodevips: ""
    nodevipips: ""
    asm_disks_exists: [ ]
    node_number: 0
  vars_files:
    - default_vars.yml

  tasks:
    - name: Generate a unique OpenSSH keypair for passwordless ssh between RAC nodes
      community.crypto.openssh_keypair:
        path: '/tmp/id_rsa'
        mode: '0700'

    - name: Build netconfig.ini variables from our RAC nodes dictionary (default_vars.yml)
      ansible.builtin.set_fact:
        nodes: "{{' '.join((nodes,item.value.vm_name))}}"
        nodeips: "{{' '.join((nodeips,item.value.vm_ip_address))}}"
        nodeprivs: "{{' '.join((nodeprivs,item.value.vm_name_priv))}}"
        nodeprivips: "{{' '.join((nodeprivips,item.value.vm_ip_address_priv))}}"
        nodevips: "{{' '.join((nodevips,item.value.vm_name_vip))}}"
        nodevipips: "{{' '.join((nodevipips,item.value.vm_ip_address_vip))}}"
      loop: "{{ lookup('dict', rac_nodes, wantlist=True) }}"

    - name: Create device strings for ASM disks from our ASM disks list (default_vars.yml)
      ansible.builtin.set_fact:
        asm_dev_strings: "/dev/deploycluster/{{ ' /dev/deploycluster/'.join(asm_disks) }}"

    - name: Build netconfig.ini file from netconfig.ini jinja template 
      ansible.builtin.template:
        src: netconfig-rac-ini.j2
        dest: /tmp/netconfig.ini
        mode: "0644"

    - name: Login to OLVM manager
      ovirt_auth:
        url: "{{ lookup('env', 'OVIRT_URL') }}"
        username: "{{ lookup('env', 'OVIRT_USERNAME') }}"
        password: "{{ lookup('env', 'OVIRT_PASSWORD') }}"
        ca_file: "{{ olvm_cafile | default('/etc/pki/ovirt-engine/ca.pem') }}"
        insecure: "{{ olvm_insecure | default(true) }}"
      tags:
        - always

    - name: Verify if ASM disk names are already in use
      ansible.builtin.include_tasks: "verify_asm.yml"
      with_items:
        - "{{ asm_disks }}"

    - name: Ask on how to continue as we detected ASM disks already in use
      ansible.builtin.pause:
        prompt: |
          Playbook paused...ASM disk(s) with name(s) {{ asm_disks_exists }} already in use. 
          Hit <ctrl-c> then <a> to abort when you want to protect the disks.
          Hit <enter> to continue when you are sure the disks can be used.
      when:
        - asm_disks_exists | length != 0

    - name: Create temporary udev rules file
      ansible.builtin.copy:
        content: ""
        dest: /tmp/70-deploycluster.rules
        mode: "0644"

    - name: Create ASM disks for Oracle RAC if not already done
      ansible.builtin.include_tasks: "build_asm.yml"
      with_items:
      - "{{ asm_disks }}"

    - name: Create RAC nodes 
      ansible.builtin.include_tasks: "build_racvm.yml"
      loop: "{{ lookup('dict', rac_nodes, wantlist=True) }}"
      loop_control:
        loop_var: node

    - name: Get content of remote netconfig.ini file
      slurp:
        src: /tmp/netconfig.ini
      register: netconfig_encoded

    - name: Get content of remote udev rules file
      slurp:
        src: /tmp/70-deploycluster.rules
      register: udev_rules_encoded

    - name: Get content of generated remote private key file
      slurp:
        src: /tmp/id_rsa
      register: id_rsa_encoded

    - name: Get content of generated remote public key file
      slurp:
        src: /tmp/id_rsa.pub
      register: id_rsa_pub_encoded

    - name: Decode remote public key file content
      set_fact:
        id_rsa_pub: "{{id_rsa_pub_encoded.content | b64decode}}"

    - name: Launch all the RAC nodes
      ansible.builtin.include_tasks: "launch_racvm.yml"
      loop: "{{ lookup('dict', rac_nodes, wantlist=True) }}"
      loop_control:
        loop_var: node


- hosts: olvm
  gather_facts: no
  vars_files:
    - default_vars.yml

  tasks:

    - name: Cleanup OLVM auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent

    - name: Remove artifacts
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      loop:
        - /tmp/id_rsa
        - /tmp/id_rsa.pub
        - /tmp/netconfig.ini
        - /tmp/70-deploycluster.rules

    - name: Print out VM logfile information
      debug:
        msg: "RAC VMs deployed, check progress with 'ssh -i ~/.ssh/<private-key> cloud-user@{{ rac_nodes.1.vm_name }} tail -f /u01/racovm/buildcluster.log'"
