---

- name: Verify if OSMH and Java already exist on the instance
  hosts: all 
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:
    - name: Collect facts about system services
      service_facts:

    - name: Check if the mgmt_agent service is already installed
      fail:
        msg: "mgmt_agent is already installed"
      when: 
      - "'mgmt_agent.service' in services"
          
    - name: Install required packages, JDK8 (minimum 1.8u281 or a later 1.8 version)
      ansible.builtin.dnf: 
        name: 
          - java-1.8.0-openjdk 
        state: latest

    - name: Install chkconfig on OL9 only
      ansible.builtin.dnf: 
        name: 
          - chkconfig
        state: latest
      when: 
      - ansible_facts['distribution_major_version'] == "9"

