---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game2048-deployment
  labels:
    app: game2048
spec:
  replicas: 3
  selector:
    matchLabels:
      app: game2048
  template:
    metadata:
      labels:
        app: game2048
    spec:
      containers:
      - name: game2048
        image: alexwhen/docker-2048
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: game2048-service
    annotations: 
    service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: "None"
    service.beta.kubernetes.io/oci-load-balancer-internal: "true"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
spec:
  selector:
    app: game2048
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
