---

- name: Delete the K8s 2048 Game application
  hosts: ocne_op
  gather_facts: false

  tasks:

  - name: Delete the 2048 Game OCI Loadbalancer
    command: kubectl delete svc game2048-service
    environment:
      KUBECONFIG: "kubeconfig.ocne_env.{{ ocne_k8s }}"

  - name: Delete the 2048 Game OCI Deployment
    command: kubectl delete deployment game2048-deployment
    environment:
      KUBECONFIG: "kubeconfig.ocne_env.{{ ocne_k8s }}"

