---
- hosts: all
  tasks:
  - name: Install apache packages 
    dnf:
      name: httpd
      state: present

  - name: ensure httpd is running
    ansible.builtin.service:
      name: httpd 
      state: started

  - name: Open port 80 for http access
    firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled

  - name: Restart the firewalld service to load in the firewall changes
    service: 
      name: firewalld 
      state: restarted
      enabled: yes
